-- TMA1 Flow aggregations for GenAI observability.
-- Executed by tma1-server on first start (idempotent — uses IF NOT EXISTS).
--
-- Two data paths:
--   1. Claude Code → OTel metrics (claude_code_* tables, auto-created) + logs (opentelemetry_logs)
--      These tables are auto-created by GreptimeDB when OTLP data arrives. No flows needed.
--   2. Other agents (GenAI SDK) → OTel traces (opentelemetry_traces, auto-created)
--      Flows below derive per-minute aggregations from traces.
--
-- Source table for flows (auto-created by GreptimeDB when trace data arrives):
--   opentelemetry_traces — OTel spans with GenAI semantic convention attributes

-- =============================================================================
-- Sink tables (for traces-based flows)
-- =============================================================================

CREATE TABLE IF NOT EXISTS tma1_token_usage_1m (
    model         STRING,
    request_count INT64,
    input_tokens  DOUBLE,
    output_tokens DOUBLE,
    time_window   TIMESTAMP TIME INDEX,
    PRIMARY KEY (model)
);

CREATE TABLE IF NOT EXISTS tma1_cost_1m (
    model    STRING,
    cost_usd DOUBLE,
    time_window TIMESTAMP TIME INDEX,
    PRIMARY KEY (model)
);

CREATE TABLE IF NOT EXISTS tma1_latency_1m (
    model           STRING,
    request_count   INT64,
    duration_sketch BINARY,
    time_window     TIMESTAMP TIME INDEX,
    PRIMARY KEY (model)
);

CREATE TABLE IF NOT EXISTS tma1_status_1m (
    model         STRING,
    request_count INT64,
    error_count   INT64,
    time_window   TIMESTAMP TIME INDEX,
    PRIMARY KEY (model)
);

CREATE TABLE IF NOT EXISTS tma1_model_pricing (
    model_pattern STRING PRIMARY KEY,
    priority      INT32,
    input_price   DOUBLE,
    output_price  DOUBLE,
    ts            TIMESTAMP TIME INDEX DEFAULT '2024-01-01T00:00:00Z'
);

-- =============================================================================
-- Flows (continuous aggregation from traces)
-- These only activate when opentelemetry_traces exists (i.e., when agents
-- using standard GenAI SDK send trace data).
-- =============================================================================

-- 1. Token usage per model per minute.
CREATE FLOW IF NOT EXISTS tma1_token_usage_flow
SINK TO tma1_token_usage_1m
EXPIRE AFTER '7d'
COMMENT 'Token usage per model per minute, derived from GenAI spans'
AS
SELECT
    "span_attributes.gen_ai.request.model"                                AS model,
    COUNT("span_attributes.gen_ai.request.model")                         AS request_count,
    SUM(CAST("span_attributes.gen_ai.usage.input_tokens" AS DOUBLE))      AS input_tokens,
    SUM(CAST("span_attributes.gen_ai.usage.output_tokens" AS DOUBLE))     AS output_tokens,
    date_bin('1 minute'::INTERVAL, "timestamp")                           AS time_window
FROM opentelemetry_traces
WHERE "span_attributes.gen_ai.system" IS NOT NULL
GROUP BY "span_attributes.gen_ai.request.model", time_window;

-- 2. Cost flow is dynamically generated by Go code (see flows.go InitCostFlow).
-- It uses pricing from tma1_model_pricing table.

-- 3. Latency distribution per model per minute (uddsketch for percentile queries).
CREATE FLOW IF NOT EXISTS tma1_latency_flow
SINK TO tma1_latency_1m
EXPIRE AFTER '7d'
COMMENT 'Latency distribution per model per minute, derived from GenAI spans'
AS
SELECT
    "span_attributes.gen_ai.request.model"        AS model,
    COUNT("span_attributes.gen_ai.request.model")  AS request_count,
    uddsketch_state(128, 0.01, duration_nano)      AS duration_sketch,
    date_bin('1 minute'::INTERVAL, "timestamp")    AS time_window
FROM opentelemetry_traces
WHERE "span_attributes.gen_ai.system" IS NOT NULL
GROUP BY "span_attributes.gen_ai.request.model", time_window;

-- 4. Request count + error count per model per minute.
CREATE FLOW IF NOT EXISTS tma1_status_flow
SINK TO tma1_status_1m
EXPIRE AFTER '7d'
COMMENT 'Request and error counts per model per minute, derived from GenAI spans'
AS
SELECT
    "span_attributes.gen_ai.request.model" AS model,
    COUNT(1) AS request_count,
    SUM(CASE WHEN span_status_code = 'STATUS_CODE_ERROR' THEN 1 ELSE 0 END) AS error_count,
    date_bin('1 minute'::INTERVAL, "timestamp") AS time_window
FROM opentelemetry_traces
WHERE "span_attributes.gen_ai.system" IS NOT NULL
GROUP BY "span_attributes.gen_ai.request.model", time_window;
